### ISSUE TITLE
"lita-github-pinger"

### ISSUE THREAD

**Issue by dg-ratiodata** [Everlane/everbot#3]
Is it possible that "lita-github-pinger" is a private repository? You can find it on rubygems but not in your organization.

**Comment by taylorlapeyre** [comment]
@dg-ratiodata Yep! lita-github-pinger is private. We'll be open sourcing it before the end of the day.

**Comment by taylorlapeyre** [comment]
@dg-ratiodata https://github.com/Everlane/lita-github-pinger

**Comment by dg-ratiodata** [comment]
Perfect. Thanks a lot.
